### ISSUE TITLE
psamm-import command not found

### ISSUE THREAD

**Issue by arturomarin** [zhanglab/psamm#218]
Hello to everybody,

when I try import SBML files in PSAMM the terminal not found the command psamm-import.

```
(PSAMM) arturo@arturo-HP:~/Modelos/PSAMM_pruebas$ psamm-import sbml --source e_coli_core.xml --dest E_coli_yaml
psamm-import: no se encontró la orden

```

**Comment by jonls** [comment]
Have you installed the psamm-import package? The psamm-import command is provided by a separate package that can be installed with: `pip install git+https://github.com/zhanglab/psamm-import.git`.

**Comment by arturomarin** [comment]
Ok, thanks. I apologize, I did not see this part of the documentation.

The best
