### ISSUE TITLE
How to add reactions identified by gap fill to model

### ISSUE THREAD

**Issue by mmundy42** [zhanglab/psamm#264]
Is there an easy way to add the reactions reported by the gapfill or fastgapfill commands to a model? And do you need to add the artificial transporters and exchanges too?

**Comment by keitht547** [comment]
Hi @mmundy42,
If your gap filling is being done on a model with a larger database of reactions available to gap fill from, then adding the reactions to your current model would just require you to add in the reaction ID of the identified reactions to your model definition file that defines the subset of reactions in the model. Information on the model definition subset can be found here along with info on the other components of the model: https://psamm.readthedocs.io/en/stable/file_format.html#model-definition

As for the artificial exchange reactions these would need to be added in manually to the exchange definition for the artificial exchange reactions by creating a new entry for the compound identified in the gapfilling artificial reaction. The artificial transporters would require you to add in a new reaction entry to the reconstruction manually in your reactions file and then add in the new ID to your model definition file as well. 

If you need any additional information on the files and how to format new entries our documentation describes what information is needed for different pieces of a reconstruction and provides examples of entries from these different files. https://psamm.readthedocs.io/en/stable/file_format.html

If you have any further questions feel free to contact us. 
Thank you, 
Keith
