### ISSUE TITLE
Rename --reaction options to --objective

### ISSUE THREAD

**Issue by jonls** [zhanglab/psamm#30]
For `fba`, `robustness`, `fva` and similar commands there is an option called `--reaction` to select a different reaction to optimize than the biomass reaction specified in `model.yaml`. The name of this option is not very descriptive. `--objective` seems to be a better choice.

Other options: `--maximize`, `--optimize`, `--biomass`...

**Comment by jonls** [comment]
@keitht547 thoughts?

**Comment by yingzhanguri** [comment]
I like --objective or --optimize.

On 9/10/15 5:40 PM, Jon Lund Steffensen wrote:
>
> For |fba|, |robustness|, |fva| and similar commands there is an option 
> called |--reaction| to select a different reaction to optimize than 
> the biomass reaction specified in |model.yaml|. The name of this 
> option is not very descriptive. |--objective| seems to be a better choice.
>
> Other options: |--maximize|, |--optimize|, |--biomass|...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zhanglab/psamm/issues/30>.
>

-- 
*** New email address: yingzhang@uri.edu ***
--
Ying Zhang
Assistant Professor
Department of Cell and Molecular Biology
College of the Environment and Life Sciences
University of Rhode Island

**Comment by keitht547** [comment]
I like --objective too. I think it makes it pretty clear what it is. especially with robustness where there can be two user defined reactions in the input
